version: '3.1'

services:
  smart_house_auth:
    image: postgres:latest
    environment:
      POSTGRES_DB: smart_house_auth
      POSTGRES_USER: rsushe
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data_auth
  smart_house_core:
    image: postgres:latest
    environment:
      POSTGRES_DB: smart_house_core
      POSTGRES_USER: rsushe
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data_core
  my-redis-stack:
    image: redis:latest
    container_name: my-redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:my-redis-stack:6379
    ports:
      - "8081:8081"

volumes:
  my_db_volume:
