ktor:
  application:
    modules:
      - com.smart.house.core.SmartHouseCoreApplicationKt.module
  deployment:
    port: 8081
  client:
    auth:
      host: "http://localhost:8080"
    db:
      host: "http://localhost:8082"
